#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""scaffold_cli.py — 模块脚手架生成器（开发阶段技能主动驱动 T4）

行业锚定：BP-04 Spotify Backstage Scaffold
技能依赖：impl-coach（domain/module-scaffold.md 模板定义）

CLI：
  python3 tools/scaffold_cli.py create --name orders --layer business --lang python
  python3 tools/scaffold_cli.py create --name orders --layer business --lang python --dry-run
  python3 tools/scaffold_cli.py create --name orders --layer business --lang python --adr-ref ADR-002
  python3 tools/scaffold_cli.py templates
"""
import os
import sys
import argparse
import datetime

ROOT = os.environ.get("PROJECT_ROOT",
                       os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

LAYERS = {
    "presentation": {
        "label": "Presentation",
        "allowed_deps": ["business"],
        "python_files": ["router.py", "dto.py", "__init__.py"],
        "ts_files": ["{name}.controller.ts", "{name}.dto.ts", "index.ts"],
        "test_files_py": ["tests/test_router.py"],
        "test_files_ts": ["__tests__/{name}.controller.spec.ts"],
    },
    "business": {
        "label": "Business",
        "allowed_deps": ["data"],
        "python_files": ["interface.py", "service.py", "dto.py",
                         "repository.py", "exceptions.py", "__init__.py"],
        "ts_files": ["{name}.interface.ts", "{name}.service.ts",
                     "{name}.dto.ts", "{name}.repository.ts",
                     "{name}.exceptions.ts", "index.ts"],
        "test_files_py": ["tests/test_service.py", "tests/test_repository.py",
                          "tests/conftest.py"],
        "test_files_ts": ["__tests__/{name}.service.spec.ts"],
    },
    "data": {
        "label": "Data",
        "allowed_deps": [],
        "python_files": ["repository_impl.py", "models.py", "__init__.py"],
        "ts_files": ["{name}.repository.impl.ts", "{name}.models.ts", "index.ts"],
        "test_files_py": ["tests/test_repository_impl.py"],
        "test_files_ts": ["__tests__/{name}.repository.impl.spec.ts"],
    },
}


def _class_name(name):
    return "".join(w.capitalize() for w in name.replace("-", "_").split("_"))


def _header_py(module, adr_refs, desc=""):
    lines = [f'"""{module} - {desc}', ""]
    if adr_refs:
        lines.append("Architecture constraints:")
        for ref in adr_refs:
            lines.append(f"  - {ref}")
    lines.extend(["", f"Generated by scaffold_cli on {datetime.date.today().isoformat()}", '"""', ""])
    return "\n".join(lines)


def _header_ts(module, adr_refs, desc=""):
    lines = [f"// {module} - {desc}"]
    if adr_refs:
        lines.append("// Architecture constraints: " + ", ".join(adr_refs))
    lines.extend([f"// Generated by scaffold_cli on {datetime.date.today().isoformat()}", ""])
    return "\n".join(lines)


# ─── Python generators ──────────────────────────────────────

def _py_init(m, a, l): return _header_py(m, a, "package init")

def _py_interface(m, a, l):
    c = _class_name(m)
    return f'''{_header_py(m, a, f"{m} service interface")}
from typing import Protocol
from .dto import {c}Request, {c}Response


class {c}Service(Protocol):
    """{m} service interface"""
    async def create(self, request: {c}Request) -> {c}Response: ...
    async def get_by_id(self, id: str) -> {c}Response | None: ...
    async def update(self, id: str, request: {c}Request) -> {c}Response: ...
    async def delete(self, id: str) -> None: ...
'''

def _py_service(m, a, l):
    c = _class_name(m)
    return f'''{_header_py(m, a, f"{m} service implementation")}
from .interface import {c}Service
from .dto import {c}Request, {c}Response
from .repository import {c}Repository


class {c}ServiceImpl:
    def __init__(self, repository: {c}Repository):
        self._repository = repository

    async def create(self, request: {c}Request) -> {c}Response:
        # TODO: implement
        raise NotImplementedError

    async def get_by_id(self, id: str) -> {c}Response | None:
        # TODO: implement
        raise NotImplementedError

    async def update(self, id: str, request: {c}Request) -> {c}Response:
        # TODO: implement
        raise NotImplementedError

    async def delete(self, id: str) -> None:
        # TODO: implement
        raise NotImplementedError
'''

def _py_dto(m, a, l):
    c = _class_name(m)
    return f'''{_header_py(m, a, f"{m} DTOs")}
from dataclasses import dataclass
from datetime import datetime
from typing import Optional


@dataclass
class {c}Request:
    name: str
    description: Optional[str] = None


@dataclass
class {c}Response:
    id: str
    name: str
    description: Optional[str]
    created_at: datetime
    updated_at: datetime
'''

def _py_repository(m, a, l):
    c = _class_name(m)
    return f'''{_header_py(m, a, f"{m} repository interface")}
from typing import Protocol
from .dto import {c}Response


class {c}Repository(Protocol):
    async def save(self, entity: {c}Response) -> None: ...
    async def get_by_id(self, id: str) -> {c}Response | None: ...
    async def delete(self, id: str) -> None: ...
'''

def _py_repository_impl(m, a, l):
    c = _class_name(m)
    return f'''{_header_py(m, a, f"{m} repository implementation")}
from .dto import {c}Response


class {c}RepositoryImpl:
    async def save(self, entity: {c}Response) -> None:
        # TODO: implement persistence
        raise NotImplementedError

    async def get_by_id(self, id: str) -> {c}Response | None:
        # TODO: implement query
        raise NotImplementedError

    async def delete(self, id: str) -> None:
        # TODO: implement delete
        raise NotImplementedError
'''

def _py_models(m, a, l):
    return f'{_header_py(m, a, f"{m} ORM models")}\n# TODO: define ORM models\n'

def _py_exceptions(m, a, l):
    c = _class_name(m)
    return f'''{_header_py(m, a, f"{m} exceptions")}

class {c}NotFoundError(Exception):
    def __init__(self, id: str):
        self.id = id
        super().__init__(f"{c} not found: {{id}}")


class {c}ValidationError(Exception):
    def __init__(self, field: str, message: str):
        self.field = field
        super().__init__(f"Validation error on {{field}}: {{message}}")
'''

def _py_router(m, a, l):
    c = _class_name(m)
    return f'''{_header_py(m, a, f"{m} API routes")}
from fastapi import APIRouter, Depends, HTTPException, status
from .interface import {c}Service
from .dto import {c}Request, {c}Response

router = APIRouter()


@router.post("/", response_model={c}Response, status_code=status.HTTP_201_CREATED)
async def create(request: {c}Request, service: {c}Service = Depends()):
    return await service.create(request)


@router.get("/{{id}}", response_model={c}Response)
async def get_by_id(id: str, service: {c}Service = Depends()):
    result = await service.get_by_id(id)
    if result is None:
        raise HTTPException(status_code=404, detail="{c} not found")
    return result


@router.delete("/{{id}}", status_code=status.HTTP_204_NO_CONTENT)
async def delete(id: str, service: {c}Service = Depends()):
    await service.delete(id)
'''

def _py_conftest(m, a, l):
    c = _class_name(m)
    return f'''"""Test fixtures for {m}"""
import pytest
from unittest.mock import AsyncMock
from ..repository import {c}Repository
from ..service import {c}ServiceImpl


@pytest.fixture
def mock_repository() -> AsyncMock:
    return AsyncMock(spec={c}Repository)


@pytest.fixture
def service(mock_repository) -> {c}ServiceImpl:
    return {c}ServiceImpl(repository=mock_repository)
'''

def _py_test_service(m, a, l):
    c = _class_name(m)
    return f'''"""Tests for {c}Service"""
import pytest


class Test{c}Service:
    async def test_create_not_implemented(self, service):
        with pytest.raises(NotImplementedError):
            await service.create(None)
'''

def _py_test_repository(m, a, l):
    return f'"""Repository tests"""\n\n\nclass TestRepository:\n    async def test_placeholder(self):\n        assert True\n'

def _py_test_router(m, a, l):
    return f'"""Router tests"""\n\n\nclass TestRouter:\n    async def test_placeholder(self):\n        assert True\n'

def _py_test_repo_impl(m, a, l):
    return f'"""Repository impl tests"""\n\n\nclass TestRepositoryImpl:\n    async def test_placeholder(self):\n        assert True\n'


PY_GEN = {
    "__init__.py": _py_init, "interface.py": _py_interface,
    "service.py": _py_service, "dto.py": _py_dto,
    "repository.py": _py_repository, "repository_impl.py": _py_repository_impl,
    "models.py": _py_models, "exceptions.py": _py_exceptions, "router.py": _py_router,
}
PY_TEST_GEN = {
    "tests/conftest.py": _py_conftest, "tests/test_service.py": _py_test_service,
    "tests/test_repository.py": _py_test_repository,
    "tests/test_router.py": _py_test_router,
    "tests/test_repository_impl.py": _py_test_repo_impl,
}

# ─── TypeScript generators ──────────────────────────────────

def _ts_index(m, a, l): return _header_ts(m, a, "module entry")

def _ts_interface(m, a, l):
    c = _class_name(m)
    return f'''{_header_ts(m, a, f"{m} interfaces")}
export interface I{c}Service {{
  create(req: Create{c}Dto): Promise<{c}Response>;
  getById(id: string): Promise<{c}Response | null>;
  update(id: string, req: Update{c}Dto): Promise<{c}Response>;
  delete(id: string): Promise<void>;
}}

export interface I{c}Repository {{
  save(entity: {c}Response): Promise<void>;
  getById(id: string): Promise<{c}Response | null>;
  delete(id: string): Promise<void>;
}}
'''

def _ts_service(m, a, l):
    c = _class_name(m)
    return f'''{_header_ts(m, a, f"{m} service")}
import {{ I{c}Service, I{c}Repository }} from './{m}.interface';
import {{ Create{c}Dto, Update{c}Dto, {c}Response }} from './{m}.dto';

export class {c}Service implements I{c}Service {{
  constructor(private readonly repo: I{c}Repository) {{}}
  async create(req: Create{c}Dto): Promise<{c}Response> {{ throw new Error('Not implemented'); }}
  async getById(id: string): Promise<{c}Response | null> {{ throw new Error('Not implemented'); }}
  async update(id: string, req: Update{c}Dto): Promise<{c}Response> {{ throw new Error('Not implemented'); }}
  async delete(id: string): Promise<void> {{ throw new Error('Not implemented'); }}
}}
'''

def _ts_dto(m, a, l):
    c = _class_name(m)
    return f'''{_header_ts(m, a, f"{m} DTOs")}
export interface Create{c}Dto {{ name: string; description?: string; }}
export interface Update{c}Dto {{ name?: string; description?: string; }}
export interface {c}Response {{
  id: string; name: string; description: string | null;
  createdAt: Date; updatedAt: Date;
}}
'''

def _ts_repository(m, a, l):
    c = _class_name(m)
    return f'{_header_ts(m, a, f"{m} repository")}\nexport type {{ I{c}Repository }} from \'./{m}.interface\';\n'

def _ts_repository_impl(m, a, l):
    c = _class_name(m)
    return f'''{_header_ts(m, a, f"{m} repository impl")}
import {{ I{c}Repository }} from './{m}.interface';
import {{ {c}Response }} from './{m}.dto';

export class {c}RepositoryImpl implements I{c}Repository {{
  async save(entity: {c}Response): Promise<void> {{ throw new Error('Not implemented'); }}
  async getById(id: string): Promise<{c}Response | null> {{ throw new Error('Not implemented'); }}
  async delete(id: string): Promise<void> {{ throw new Error('Not implemented'); }}
}}
'''

def _ts_models(m, a, l):
    return f'{_header_ts(m, a, f"{m} models")}\n// TODO: define ORM models\n'

def _ts_exceptions(m, a, l):
    c = _class_name(m)
    return f'''{_header_ts(m, a, f"{m} exceptions")}
export class {c}NotFoundError extends Error {{
  constructor(id: string) {{ super(`{c} not found: ${{id}}`); this.name = '{c}NotFoundError'; }}
}}
export class {c}ValidationError extends Error {{
  constructor(public readonly field: string, message: string) {{
    super(`Validation error on ${{field}}: ${{message}}`); this.name = '{c}ValidationError';
  }}
}}
'''

def _ts_controller(m, a, l):
    c = _class_name(m)
    return f'''{_header_ts(m, a, f"{m} controller")}
import {{ I{c}Service }} from './{m}.interface';
import {{ Create{c}Dto, {c}Response }} from './{m}.dto';

export class {c}Controller {{
  constructor(private readonly service: I{c}Service) {{}}
  async create(body: Create{c}Dto): Promise<{c}Response> {{ return this.service.create(body); }}
  async getById(id: string): Promise<{c}Response | null> {{ return this.service.getById(id); }}
}}
'''

def _ts_test_service(m, a, l):
    c = _class_name(m)
    return f"describe('{c}Service', () => {{ it('TODO', () => {{ expect(true).toBe(true); }}); }});\n"

def _ts_test_controller(m, a, l):
    c = _class_name(m)
    return f"describe('{c}Controller', () => {{ it('TODO', () => {{ expect(true).toBe(true); }}); }});\n"

def _ts_test_repo_impl(m, a, l):
    c = _class_name(m)
    return f"describe('{c}RepositoryImpl', () => {{ it('TODO', () => {{ expect(true).toBe(true); }}); }});\n"


TS_GEN = {
    "index.ts": _ts_index, "{name}.interface.ts": _ts_interface,
    "{name}.service.ts": _ts_service, "{name}.dto.ts": _ts_dto,
    "{name}.repository.ts": _ts_repository, "{name}.repository.impl.ts": _ts_repository_impl,
    "{name}.models.ts": _ts_models, "{name}.exceptions.ts": _ts_exceptions,
    "{name}.controller.ts": _ts_controller,
}
TS_TEST_GEN = {
    "__tests__/{name}.service.spec.ts": _ts_test_service,
    "__tests__/{name}.controller.spec.ts": _ts_test_controller,
    "__tests__/{name}.repository.impl.spec.ts": _ts_test_repo_impl,
}


def _plan_files(name, layer, lang, adr_refs):
    cfg = LAYERS[layer]
    files = []
    if lang == "python":
        src_dir = f"src/{name}"
        for fname in cfg["python_files"]:
            gen = PY_GEN.get(fname)
            if gen:
                files.append((os.path.join(src_dir, fname), gen(name, adr_refs, layer)))
        for fname in cfg["test_files_py"]:
            gen = PY_TEST_GEN.get(fname)
            if gen:
                files.append((os.path.join(src_dir, fname), gen(name, adr_refs, layer)))
    elif lang == "typescript":
        src_dir = f"src/{name}"
        for tpl in cfg["ts_files"]:
            gen = TS_GEN.get(tpl)
            if gen:
                files.append((os.path.join(src_dir, tpl.replace("{name}", name)),
                              gen(name, adr_refs, layer)))
        for tpl in cfg["test_files_ts"]:
            gen = TS_TEST_GEN.get(tpl)
            if gen:
                files.append((os.path.join(src_dir, tpl.replace("{name}", name)),
                              gen(name, adr_refs, layer)))
    return files


def cmd_create(args):
    name, layer, lang = args.name, args.layer, args.lang
    adr_refs = [r.strip() for r in (args.adr_ref or "").split(",") if r.strip()]
    patterns = [p.strip() for p in (args.patterns or "").split(",") if p.strip()]
    dry_run = args.dry_run

    if layer not in LAYERS:
        print(f"[scaffold] Unknown layer '{layer}'. Choices: {', '.join(LAYERS.keys())}")
        return 1

    files = _plan_files(name, layer, lang, adr_refs)
    if not files:
        print(f"[scaffold] No templates for layer='{layer}' lang='{lang}'")
        return 1

    print(f"[scaffold] Module scaffold plan")
    print(f"  Module: {name}  Layer: {LAYERS[layer]['label']}  Lang: {lang}  Files: {len(files)}")
    if adr_refs:
        print(f"  ADR refs: {', '.join(adr_refs)}")
    if patterns:
        print(f"  Patterns: {', '.join(patterns)}")
    for path, _ in files:
        print(f"  {'[dry-run] ' if dry_run else ''}create {path}")

    if dry_run:
        print(f"\n[scaffold] dry-run complete, no files written")
        return 0

    written = 0
    for path, content in files:
        full = os.path.join(ROOT, path)
        os.makedirs(os.path.dirname(full), exist_ok=True)
        with open(full, "w", encoding="utf-8") as f:
            f.write(content)
        written += 1
    print(f"\n[scaffold] Done: {written} files written")
    return 0


def cmd_templates(args):
    print("[scaffold] Available layer templates:")
    for key, cfg in LAYERS.items():
        print(f"\n  {key:14s} ({cfg['label']})")
        print(f"    Allowed deps: {', '.join(cfg['allowed_deps']) or 'none'}")
        print(f"    Python: {', '.join(cfg['python_files'])}")
        print(f"    TypeScript: {', '.join(cfg['ts_files'])}")
    print("\n[scaffold] Usage:")
    print("  python3 tools/scaffold_cli.py create --name orders --layer business --lang python")
    return 0


def main():
    ap = argparse.ArgumentParser(description="Module scaffold generator (T4)")
    sub = ap.add_subparsers(dest="command")
    cr = sub.add_parser("create", help="Generate module skeleton")
    cr.add_argument("--name", required=True)
    cr.add_argument("--layer", required=True, choices=LAYERS.keys())
    cr.add_argument("--lang", default="python", choices=["python", "typescript"])
    cr.add_argument("--patterns", default="")
    cr.add_argument("--adr-ref", default="")
    cr.add_argument("--dry-run", action="store_true")
    sub.add_parser("templates", help="List available templates")
    args = ap.parse_args()
    if args.command == "create":
        sys.exit(cmd_create(args))
    elif args.command == "templates":
        sys.exit(cmd_templates(args))
    else:
        ap.print_help()


if __name__ == "__main__":
    main()
